version: "3.3"

services:

  web:
    image: ghcr.io/rssiweb/website:latest
    ports:
      - 8081:80
    restart: unless-stopped

  portal:
    image: ghcr.io/rssiweb/portal:latest
    ports:
      - 8082:80
    environment:
      DB_HOST: db
      DB_NAME: ${PORTAL_DB_NAME}
      DB_USER: ${PORTAL_DB_USER}
      DB_PASSWORD: ${PORTAL_DB_PASSWORD}
      GMAIL_EMAIL: ${PORTAL_GMAIL_EMAIL}
      GMAIL_PASSWORD: ${PORTAL_GMAIL_PASSWORD}
      STORAGE_CRED: ${PORTAL_STORAGE_CRED}
    depends_on:
      - db
    restart: unless-stopped

  gsheet2db:
    image: ghcr.io/rssiweb/gsheet2db:latest
    environment:
      CREDENTIALS_SERVICE_ACCOUNT: ${GSHEET2DB_CREDENTIALS_SERVICE_ACCOUNT}
      DATABASE_URL: ${GSHEET2DB_DATABASE_URL}
    depends_on:
      - db
    restart: unless-stopped
    
  db:
    image: postgres:13
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always

  portainer:
    image: portainer/portainer-ce:2.17.1
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always

  mqtt:
    image: eclipse-mosquitto
    volumes:
      - ${MQTT_CONFIG_FILE:-./mosquitto.conf}:/mosquitto/config/mosquitto.conf
      - mqtt_data:/mosquitto/data
    ports:
      - 1883:1883
      - 9001:9001
    restart: unless-stopped

volumes:
  pg_data:
  certs:
  portainer_data:
  mqtt_data:
