name: Deploy On Production
on:
  push:
    branches: [master]
  workflow_dispatch:
  repository_dispatch:
    types: [deploy]
env:
  LETSENCRYPT_EMAIL: ${{ secrets.LETSENCRYPT_EMAIL }}
  WEB_DOMAIN: ${{ secrets.WEB_DOMAIN }}
  WEB_SALT: ${{ secrets.WEB_SALT }}
  PORTAL_DB_NAME: ${{ secrets.PORTAL_DB_NAME }}
  PORTAL_DB_USER: ${{ secrets.PORTAL_DB_USER }}
  PORTAL_DB_PASSWORD: ${{ secrets.PORTAL_DB_PASSWORD }}
  PORTAL_DOMAIN: ${{ secrets.PORTAL_DOMAIN }}
  PORTAL_GMAIL_EMAIL: ${{ secrets.PORTAL_GMAIL_EMAIL }}
  PORTAL_GMAIL_PASSWORD: ${{ secrets.PORTAL_GMAIL_PASSWORD }}
  GSHEET2DB_CREDENTIALS_SERVICE_ACCOUNT: ${{ secrets.GSHEET2DB_CREDENTIALS_SERVICE_ACCOUNT }}
  GSHEET2DB_DATABASE_URL: ${{ secrets.GSHEET2DB_DATABASE_URL }}
  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  POSTGRES_DOMAIN: ${{ secrets.POSTGRES_DOMAIN }}
  WEB_SECURE_CODE: ${{ secrets.WEB_SECURE_CODE }}
  WEB_SECURE_CODE1: ${{ secrets.WEB_SECURE_CODE1 }}
  WEB_SECURE_CODE2: ${{ secrets.WEB_SECURE_CODE2 }}
  WEB_SECURE_USER: ${{ secrets.WEB_SECURE_USER }}
  WEB_SECURE1_USER: ${{ secrets.WEB_SECURE1_USER }}
  WEB_SECURE2_USER: ${{ secrets.WEB_SECURE2_USER }}
  WEB_RAINBOW_CODE: ${{ secrets.WEB_RAINBOW_CODE }}
  WEB_INDIGO21_CODE: ${{ secrets.WEB_INDIGO21_CODE }}
  WEB_INDIGO_CODE: ${{ secrets.WEB_INDIGO_CODE }}
  PORTAINER_DOMAIN: ${{ secrets.PORTAINER_DOMAIN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create secret files
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          fingerprint: MD5:3c:c3:6f:d6:d9:6f:ca:d0:56:07:9f:4d:69:e3:25:39
          script: |
            whoami
            echo ${{ secrets.DRIVE_STORAGE_CRED }} > google-drive-cred-sa.json &&
            echo ${{ secrets.GSHEET2DB_CREDENTIALS_SERVICE_ACCOUNT }} > google-sheets-cred-sa.json
      - name: Start Deployment
        uses: TapTap21/docker-remote-deployment-action@v1.0
        with:
          remote_docker_host: ${{ secrets.SERVER }}
          ssh_private_key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.SERVER_SSH_PUBLIC_KEY }}
          stack_file_name: docker-compose.yml
          args: -p rssi up -d
