name: Deploy On Production
on:
  push:
    branches: [master]
  workflow_dispatch:
  repository_dispatch:
    types: [deploy]
env:
  LETSENCRYPT_EMAIL: ${{ secrets.LETSENCRYPT_EMAIL }}
  WEB_DOMAIN: ${{ secrets.WEB_DOMAIN }}
  WEB_SALT: ${{ secrets.WEB_SALT }}
  PORTAL_DB_NAME: ${{ secrets.PORTAL_DB_NAME }}
  PORTAL_DB_USER: ${{ secrets.PORTAL_DB_USER }}
  PORTAL_DB_PASSWORD: ${{ secrets.PORTAL_DB_PASSWORD }}
  PORTAL_DOMAIN: ${{ secrets.PORTAL_DOMAIN }}
  PORTAL_GMAIL_EMAIL: ${{ secrets.PORTAL_GMAIL_EMAIL }}
  PORTAL_GMAIL_PASSWORD: ${{ secrets.PORTAL_GMAIL_PASSWORD }}
  PORTAL_STORAGE_CRED: ${{ secrets.DRIVE_STORAGE_CRED }}
  GSHEET2DB_CREDENTIALS_SERVICE_ACCOUNT: ${{ secrets.GSHEET2DB_CREDENTIALS_SERVICE_ACCOUNT }}
  GSHEET2DB_DATABASE_URL: ${{ secrets.GSHEET2DB_DATABASE_URL }}
  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  POSTGRES_DOMAIN: ${{ secrets.POSTGRES_DOMAIN }}
  PORTAINER_DOMAIN: ${{ secrets.PORTAINER_DOMAIN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start Deployment
        uses: TapTap21/docker-remote-deployment-action@v1.0
        with:
          remote_docker_host: ${{ secrets.SERVER }}
          ssh_private_key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.SERVER_SSH_PUBLIC_KEY }}
          stack_file_name: docker-compose.yml
          args: -p rssi up -d
